### PR TITLE
fix(types): `Buffer` -> `Uint8Array`

### PR DESCRIPTION
**Pull request by joscha**
Via:

              > is it safe to assume that all occurrences of Buffer should become Uint8Array

Yes.

_Originally posted by @mtth in https://github.com/mtth/avsc/issues/452#issuecomment-2409033315_

### CODE REVIEW

**Comment by joscha** [comment]
@mtth would you mind pushing a new 6.x with this change, please?

**Comment by mtth** [comment]
@joscha - [`6.0.0-alpha.15`](https://www.npmjs.com/package/avsc/v/6.0.0-alpha.15)

**Comment by joscha** [comment]
Thank you!

**Comment by joscha** [comment]
We could catch issues like these by introducing https://github.com/tsdjs/tsd into this repository until such time that a conversion to TS (see #479) is finished.

**Pull request merged**
