### PR TITLE
node-flatbuffers benchmarking

### PR DESCRIPTION
**Pull request by rektide**
Add benchmark of [node-flatbuffers](https://github.com/evanw/node-flatbuffers).

Node-flatbuffers requires the schema to be binary compiled. I've provided both the text Coupon.fbs and the corresponding binary Coupon.bfbs.

---

Performance is pretty good. Nice job @evanw & flatbuffers designers. Benchmark result that I casually generated (Chrome, &c still running) on my i7-4750HQ, /w NodeSource's release of Node.js 6.9.4 for Debian Jessie:

```
decode "Coupon"
avsc x 1,191,823 ops/sec ±1.05% (88 runs sampled)
flatbuffers x 1,607,514 ops/sec ±0.93% (94 runs sampled)
json x 361,253 ops/sec ±1.16% (91 runs sampled)
msgpackLite x 103,161 ops/sec ±1.19% (91 runs sampled)
protobufjs x 1,515,488 ops/sec ±0.89% (88 runs sampled)
protocolBuffers x 620,420 ops/sec ±1.32% (90 runs sampled)
schemapack x 1,117,342 ops/sec ±0.91% (94 runs sampled)
encode "Coupon"
avsc x 757,858 ops/sec ±1.38% (89 runs sampled)
flatbuffers x 514,465 ops/sec ±1.30% (88 runs sampled)
json x 84,345 ops/sec ±0.63% (93 runs sampled)
msgpackLite x 109,579 ops/sec ±3.46% (74 runs sampled)
protobufjs x 919,021 ops/sec ±0.84% (92 runs sampled)
protocolBuffers x 509,717 ops/sec ±0.89% (89 runs sampled)
schemapack x 725,136 ops/sec ±0.71% (93 runs sampled)
```
---

This was super easy to implement. Thanks for the great job @mtth. Very good initiative to start getting some numbers on this critical serialization task. Have you considered maybe moving this codebase outside of avsc and into it's own project? There doesn't seem to be a lot out there, and your implementation is nice & clean.

### CODE REVIEW

**Comment by mtth** [comment]
Thanks!

Would you mind submitting this PR against the `5.0` branch actually? I'm about to do a new release (and `master`'s benchmarks don't handle the latest version of `protobufjs` correctly, it's "cheating" by skipping fields). You'll need to update a few of `Coupon`'s field names (from underscore-case to camel-case).

**Comment by mtth** [comment]
It looks like you'll also need to update your enum declarations, the schema doesn't compile currently ([reference doc](https://google.github.io/flatbuffers/md__schemas.html)).

Also, I don't think the numbers you mention above are meaningful; the data doesn't match (half the fields are missing after a serialization-deserialization roundtrip). Here are a few representative numbers after fixing this:

```
decode "Coupon"                
avsc x 1,343,064 ops/sec ±1.76% (82 runs sampled)                     
flatbuffers x 640,737 ops/sec ±1.42% (89 runs sampled)                        
json x 392,039 ops/sec ±1.73% (82 runs sampled)
msgpackLite x 91,116 ops/sec ±1.65% (86 runs sampled)                 
protobufjs x 1,012,960 ops/sec ±1.67% (89 runs sampled)                     
protocolBuffers x 782,477 ops/sec ±1.41% (83 runs sampled)
schemapack x 1,108,487 ops/sec ±1.54% (90 runs sampled)
encode "Coupon"    
avsc x 874,505 ops/sec ±1.78% (84 runs sampled)
flatbuffers x 308,196 ops/sec ±0.48% (80 runs sampled)
json x 231,390 ops/sec ±1.27% (95 runs sampled)
msgpackLite x 109,550 ops/sec ±2.55% (82 runs sampled)
protobufjs x 772,621 ops/sec ±1.66% (84 runs sampled)
protocolBuffers x 486,580 ops/sec ±0.89% (94 runs sampled)
schemapack x 729,885 ops/sec ±1.55% (84 runs sampled)
```

Finally, to be fully fair, the benchmark should convert `flatbuffer`'s returned `Uint8Array` into an actual `Buffer` object.

**Comment by rektide** [comment]
Schema error fixed. I just committed a fix to convert to an array. Ouch, that hurt. :)

I'll look at the round tripping issue. Nothing immediately jumps out at me.

**Comment by mtth** [comment]
Hey @rektide - do you think you'll have time to make the couple changes above?

**Comment by mtth** [comment]
Fixed and merged in 9ac855416e299e541f346183bdc04cea9b2a1c1e.

**Pull request closed without merging**
